/**
 * Mock/fallback data for Kit Builder
 * Used when external DB is unavailable
 */

import type { KitBox, KitItem } from "./types";

export const MOCK_BOXES: KitBox[] = [
  {
    id: 'mock-box-1',
    name: 'Caixa Kraft P',
    sku: 'CX-KRAFT-P',
    imageUrl: null,
    price: 4.5,
    internalWidth: 15,
    internalHeight: 10,
    internalDepth: 8,
    internalVolume: 1200,
    material: 'Papel Kraft',
    weight: 120,
  },
  {
    id: 'mock-box-2',
    name: 'Caixa Kraft M',
    sku: 'CX-KRAFT-M',
    imageUrl: null,
    price: 7.9,
    internalWidth: 25,
    internalHeight: 15,
    internalDepth: 12,
    internalVolume: 4500,
    material: 'Papel Kraft',
    weight: 200,
  },
  {
    id: 'mock-box-3',
    name: 'Caixa Kraft G',
    sku: 'CX-KRAFT-G',
    imageUrl: null,
    price: 12.5,
    internalWidth: 35,
    internalHeight: 20,
    internalDepth: 15,
    internalVolume: 10500,
    material: 'Papel Kraft',
    weight: 350,
  },
  {
    id: 'mock-box-4',
    name: 'Caixa Premium Preta M',
    sku: 'CX-PREM-M',
    imageUrl: null,
    price: 15.0,
    internalWidth: 28,
    internalHeight: 18,
    internalDepth: 12,
    internalVolume: 6048,
    material: 'Papelão Revestido',
    weight: 280,
  },
];

export const MOCK_ITEMS: KitItem[] = [
  {
    id: 'mock-item-1',
    name: 'Caneca Cerâmica 350ml',
    sku: 'CAN-CER-350',
    imageUrl: null,
    price: 18.9,
    width: 9,
    height: 10,
    depth: 9,
    volume: 810,
    weight: 320,
    material: 'Cerâmica',
    category: 'Canecas',
    quantity: 1,
    isOptional: false,
    isReplaceable: false,
    allowsPersonalization: true,
  },
  {
    id: 'mock-item-2',
    name: 'Caderno A5 Capa Dura',
    sku: 'CAD-A5-CD',
    imageUrl: null,
    price: 22.5,
    width: 15,
    height: 21,
    depth: 2,
    volume: 630,
    weight: 250,
    material: 'Papel / Couro Sintético',
    category: 'Cadernos',
    quantity: 1,
    isOptional: false,
    isReplaceable: true,
    allowsPersonalization: true,
  },
  {
    id: 'mock-item-3',
    name: 'Caneta Metal Premium',
    sku: 'CAN-MET-P',
    imageUrl: null,
    price: 12.0,
    width: 1.5,
    height: 14,
    depth: 1.5,
    volume: 31.5,
    weight: 35,
    material: 'Metal',
    category: 'Canetas',
    quantity: 1,
    isOptional: false,
    isReplaceable: true,
    allowsPersonalization: true,
  },
  {
    id: 'mock-item-4',
    name: 'Garrafa Térmica 500ml',
    sku: 'GAR-TERM-500',
    imageUrl: null,
    price: 35.0,
    width: 7,
    height: 25,
    depth: 7,
    volume: 1225,
    weight: 280,
    material: 'Aço Inox',
    category: 'Garrafas',
    quantity: 1,
    isOptional: true,
    isReplaceable: false,
    allowsPersonalization: true,
  },
  {
    id: 'mock-item-5',
    name: 'Necessaire Nylon',
    sku: 'NEC-NYL-01',
    imageUrl: null,
    price: 14.0,
    width: 20,
    height: 12,
    depth: 6,
    volume: 1440,
    weight: 80,
    material: 'Nylon',
    category: 'Acessórios',
    quantity: 1,
    isOptional: true,
    isReplaceable: false,
    allowsPersonalization: true,
  },
  {
    id: 'mock-item-6',
    name: 'Pen Drive 16GB',
    sku: 'PEN-16GB',
    imageUrl: null,
    price: 19.9,
    width: 6,
    height: 2,
    depth: 1,
    volume: 12,
    weight: 15,
    material: 'Plástico / Metal',
    category: 'Tecnologia',
    quantity: 1,
    isOptional: true,
    isReplaceable: true,
    allowsPersonalization: true,
  },
];
