-- =====================================================================
-- BLOCO 11 — CRON JOBS (pg_cron)
-- =====================================================================
-- Inspeção:
--   SELECT count(*) FROM cron.job;  -> 0
--
-- NENHUM cron job está atualmente registrado em `cron.job` neste projeto.
--
-- ATENÇÃO: Cron jobs NÃO fazem parte de um pg_dump tradicional — eles são
-- estado runtime gerenciado por `cron.schedule(...)`. Se houver jobs em
-- outros ambientes (staging/prod), inspecione lá com:
--
--   SELECT jobid, jobname, schedule, command, active
--   FROM cron.job ORDER BY jobid;
--
-- ---------------------------------------------------------------------
-- Pré-requisitos (já atendidos pelo Bloco 8):
--   CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
--   CREATE EXTENSION IF NOT EXISTS pg_net  WITH SCHEMA extensions;
-- ---------------------------------------------------------------------
--
-- TEMPLATE para invocar uma edge function por HTTP a cada N minutos.
-- Substitua <PROJECT_REF>, <FUNCTION_NAME> e <ANON_KEY>.
-- NÃO commitar a anon key no repositório — usar Supabase Vault em prod:
--   SELECT vault.create_secret('https://<project>.supabase.co/...', 'edge_url');
--   SELECT vault.create_secret('<anon_key>', 'edge_anon_key');
--
-- ---- EXEMPLO 1: invocar edge function a cada minuto ----
-- SELECT cron.schedule(
--   'webhook-alerts-monitor',
--   '* * * * *',
--   $$
--   SELECT net.http_post(
--     url     := 'https://<PROJECT_REF>.supabase.co/functions/v1/webhook-alerts-monitor',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'apikey',       '<ANON_KEY>',
--       'Authorization','Bearer <ANON_KEY>'
--     ),
--     body    := jsonb_build_object('triggered_at', now())
--   );
--   $$
-- );
--
-- ---- EXEMPLO 2: rodar SQL puro a cada 15 minutos ----
-- SELECT cron.schedule(
--   'auto-revoke-orphan-full-keys',
--   '*/15 * * * *',
--   $$ SELECT public.auto_revoke_orphan_full_keys(); $$
-- );
--
-- ---- Para REMOVER um job: ----
-- SELECT cron.unschedule('webhook-alerts-monitor');
--
-- ---- Para LISTAR e ver histórico: ----
-- SELECT * FROM cron.job;
-- SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 50;
-- =====================================================================
