import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
        "3xl": "1600px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
          glow: "hsl(var(--primary-glow))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        cart: {
          DEFAULT: "hsl(var(--cart))",
          hover: "hsl(var(--cart-hover))",
          foreground: "hsl(var(--cart-foreground))",
        },
        orange: {
          DEFAULT: "hsl(var(--orange))",
          hover: "hsl(var(--orange-hover))",
          active: "hsl(var(--orange-active))",
          glow: "hsl(var(--orange-glow))",
          foreground: "hsl(var(--orange-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        // Semantic colors
        surface: {
          DEFAULT: "hsl(var(--surface))",
          hover: "hsl(var(--surface-hover))",
        },
        "text-secondary": "hsl(var(--text-secondary))",
        interactive: "hsl(var(--interactive))",
        divider: "hsl(var(--divider))",
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        overlay: {
          DEFAULT: "hsl(var(--overlay-color) / var(--overlay-opacity))",
          blur: "var(--overlay-blur)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          elevated: "hsl(var(--card-elevated))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Status indicators (replacing gamification colors)
        status: {
          active: "hsl(var(--success))",
          pending: "hsl(var(--warning))",
          inactive: "hsl(var(--muted-foreground))",
        },
        // Chart colors
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        // Cores de produtos
        product: {
          red: "hsl(var(--color-red))",
          blue: "hsl(var(--color-blue))",
          green: "hsl(var(--color-green))",
          white: "hsl(var(--color-white))",
          black: "hsl(var(--color-black))",
          orange: "hsl(var(--primary))",
          yellow: "hsl(var(--warning))",
          pink: "hsl(var(--color-pink))",
          gray: "hsl(var(--color-gray))",
          silver: "hsl(var(--color-silver))",
          brown: "hsl(var(--color-brown))",
          purple: "hsl(var(--color-purple))",
        },
      },
      backgroundImage: {
        // Gradient tokens — SSOT em src/index.css (--gradient-*)
        "gradient-primary": "var(--gradient-primary)",
        "gradient-cta": "var(--gradient-cta)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-glow": "var(--gradient-glow)",
        "gradient-subtle": "var(--gradient-subtle)",
        "gradient-secondary-token": "var(--gradient-secondary)",
        "gradient-success-token": "var(--gradient-success)",
        "gradient-highlight": "var(--gradient-highlight)",
        "gradient-card": "var(--gradient-card)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "calc(var(--radius-2xl) + 8px)",
        full: "var(--radius-full)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width)",
        hairline: "var(--border-width-hairline)",
        strong: "var(--border-width-strong)",
        "0": "0px",
        "2": "var(--border-width-strong)",
        "4": "4px",
        "8": "8px",
      },
      spacing: {
        card: "var(--spacing-card)",
        "card-sm": "var(--spacing-card-sm)",
        "card-lg": "var(--spacing-card-lg)",
        section: "var(--spacing-section)",
        "section-lg": "var(--spacing-section-lg)",
      },
      boxShadow: {
        xs: "0 1px 2px hsl(var(--primary) / 0.05)",
        sm: "var(--shadow-soft)",
        md: "var(--shadow-medium)",
        lg: "var(--shadow-lg, 0 10px 15px -3px hsl(var(--primary) / 0.1))",
        xl: "var(--shadow-premium)",
        glow: "var(--shadow-glow)",
        "glow-hover": "var(--shadow-glow-hover)",
        "glow-active": "var(--shadow-glow-active)",
        "glow-focus": "var(--shadow-glow-focus)",
        "premium-hover": "var(--shadow-premium-hover)",
        "glow-primary": "var(--shadow-glow)",
        "glow-secondary": "0 0 25px hsl(var(--secondary) / 0.3)",
        "glow-success": "0 0 25px hsl(var(--success) / 0.3)",
        "glow-warning": "0 0 25px hsl(var(--warning) / 0.3)",
        "glow-orange": "var(--shadow-glow)",
        "glow-cart": "0 0 25px hsl(var(--cart) / 0.4)",
        header: "var(--shadow-header)",
        elevated: "var(--shadow-premium)",
      },
      transitionDuration: {
        "150": "150ms",
        "200": "var(--duration-fast)",
        "250": "250ms",
        "300": "var(--duration-normal)",
        "400": "400ms",
        "500": "var(--duration-slow)",
      },
      transitionTimingFunction: {
        "bounce-in": "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        smooth: "var(--ease-in-out)",
        spring: "var(--ease-out)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.8)", opacity: "0.5" },
          "50%": { transform: "scale(1.2)", opacity: "0" },
          "100%": { transform: "scale(0.8)", opacity: "0.5" },
        },
        "bounce-in": {
          "0%": { transform: "scale(0.3)", opacity: "0" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "slide-down": {
          from: { transform: "translateY(-10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "slide-left": {
          from: { transform: "translateX(10px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "slide-right": {
          from: { transform: "translateX(-10px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 5px hsl(var(--primary) / 0.3)" },
          "50%": { boxShadow: "0 0 20px hsl(var(--primary) / 0.6)" },
        },
        "border-glow": {
          "0%, 100%": { borderColor: "hsl(var(--primary) / 0.3)" },
          "50%": { borderColor: "hsl(var(--primary) / 0.8)" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        pop: {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)" },
        },
        "count-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "sound-wave": {
          "0%, 100%": { height: "4px" },
          "50%": { height: "16px" },
        },
      },
      animation: {
        "accordion-down": "accordion-down var(--duration-normal) var(--ease-out)",
        "accordion-up": "accordion-up var(--duration-normal) var(--ease-out)",
        "pulse-ring": "pulse-ring 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-in": "bounce-in 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        "slide-up": "slide-up 0.3s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
        "slide-left": "slide-left 0.3s ease-out",
        "slide-right": "slide-right 0.3s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
        float: "float 3s ease-in-out infinite",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
        "border-glow": "border-glow 2s ease-in-out infinite",
        wiggle: "wiggle 0.3s ease-in-out",
        pop: "pop 0.3s ease-out",
        "count-up": "count-up 0.4s ease-out forwards",
        "spin-slow": "spin-slow 3s linear infinite",
        "sound-wave": "sound-wave 0.5s ease-in-out infinite",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
