// Exporting all hooks from kit-builder
export * from "@/hooks/kit-builder/useCustomKitPersistence";
export * from "@/hooks/kit-builder/useCustomKitsRealtime";
export * from "@/hooks/kit-builder/useDuplicateKitDetector";
export * from "@/hooks/kit-builder/useKitAutoSave";
export * from "@/hooks/kit-builder/useKitBuilder";
export * from "@/hooks/kit-builder/useKitBuilderPageState";
export * from "@/hooks/kit-builder/useKitBuilderQueries";
export * from "@/hooks/kit-builder/useKitBuilderTransformers";
export * from "@/hooks/kit-builder/useKitCollaboration";
export * from "@/hooks/kit-builder/useKitIdentitySuggestion";
export * from "@/hooks/kit-builder/useKitStockForecast";
export * from "@/hooks/kit-builder/useKitStockValidation";
export * from "@/hooks/kit-builder/useKitTemplates";
export * from "@/hooks/kit-builder/useKitUndoRedo";
export * from "@/hooks/kit-builder/useKitVariants";
export * from "@/hooks/kit-builder/useKitWizardShortcuts";
export * from "@/hooks/kit-builder/useSimilarKits";
export * from "@/hooks/kit-builder/useTemplateSnapshot";
