import { z } from 'zod';

export const productFormSchema = z.object({
  // Info básica
  sku: z.string().trim().min(1, 'SKU é obrigatório').max(50, 'SKU muito longo'),
  name: z.string().trim().min(1, 'Nome é obrigatório').max(300, 'Nome muito longo'),
  description: z.string().max(5000, 'Descrição muito longa').optional().default(''),
  short_description: z.string().max(500, 'Descrição curta muito longa').optional().default(''),
  brand: z.string().max(100).optional().default(''),

  // Categoria e fornecedor (IDs reais do BD externo)
  category_id: z.string().optional().default(''),
  supplier_id: z.string().min(1, 'Fornecedor é obrigatório'),
  supplier_reference: z.string().max(100).optional().default(''),
  supplier_product_url: z.string().max(500).optional().default(''),

  // Preço e estoque
  sale_price: z.coerce.number().min(0, 'Preço não pode ser negativo').default(0),
  cost_price: z.coerce.number().min(0).optional().default(0),
  suggested_price: z.coerce.number().min(0).optional().nullable(),
  stock_quantity: z.coerce.number().int().min(0).default(10000),
  min_quantity: z.coerce.number().int().min(1).default(1),
  min_order_quantity: z.coerce.number().int().min(0).optional().nullable(),
  stock_unit: z.string().max(20).optional().default('un'),

  // Dimensões físicas
  height_cm: z.coerce.number().min(0).optional().nullable(),
  width_cm: z.coerce.number().min(0).optional().nullable(),
  length_cm: z.coerce.number().min(0).optional().nullable(),
  diameter_cm: z.coerce.number().min(0).optional().nullable(),
  weight_g: z.coerce.number().min(0).optional().nullable(),
  capacity_ml: z.coerce.number().min(0).optional().nullable(),

  // Dimensões internas
  internal_height_cm: z.coerce.number().min(0).optional().nullable(),
  internal_width_cm: z.coerce.number().min(0).optional().nullable(),
  internal_length_cm: z.coerce.number().min(0).optional().nullable(),
  internal_diameter_cm: z.coerce.number().min(0).optional().nullable(),

  // Embalagem
  packing_type: z.string().max(100).optional().default(''),
  box_width_mm: z.coerce.number().min(0).optional().nullable(),
  box_height_mm: z.coerce.number().min(0).optional().nullable(),
  box_length_mm: z.coerce.number().min(0).optional().nullable(),
  box_weight_kg: z.coerce.number().min(0).optional().nullable(),
  box_quantity: z.coerce.number().int().min(0).optional().nullable(),
  box_inner_quantity: z.coerce.number().int().min(0).optional().nullable(),
  box_volume_cm3: z.coerce.number().min(0).optional().nullable(),
  box_internal_height_cm: z.coerce.number().min(0).optional().nullable(),
  box_internal_width_cm: z.coerce.number().min(0).optional().nullable(),
  box_internal_length_cm: z.coerce.number().min(0).optional().nullable(),

  // Embalagem detalhes
  packaging_material: z.string().max(100).optional().default(''),
  packaging_color: z.string().max(100).optional().default(''),
  packaging_finish: z.string().max(100).optional().default(''),

  // Flags existentes
  is_active: z.boolean().default(true),
  is_featured: z.boolean().default(false),
  is_bestseller: z.boolean().default(false),
  is_new: z.boolean().default(false),
  is_on_sale: z.boolean().default(false),

  // Expirações dos flags (null = sem limite)
  is_featured_expires_at: z.string().nullable().optional().default(null),
  is_bestseller_expires_at: z.string().nullable().optional().default(null),
  is_new_expires_at: z.string().nullable().optional().default(null),
  is_on_sale_expires_at: z.string().nullable().optional().default(null),
  is_kit: z.boolean().default(false),
  has_commercial_packaging: z.boolean().default(false),

  // Flags novas
  is_imported: z.boolean().default(false),
  is_textil: z.boolean().default(false),
  is_thermal: z.boolean().default(false),
  allows_personalization: z.boolean().default(true),
  has_gift_box: z.boolean().default(false),
  has_optional_packaging: z.boolean().default(false),

  // Fiscal
  ncm_code: z.string().max(20).optional().default(''),
  ean: z.string().max(20).optional().default(''),
  gtin: z.string().max(20).optional().default(''),
  ipi_rate: z.coerce.number().min(0).optional().nullable(),
  country_of_origin: z.string().max(100).optional().default(''),
  cfop: z.string().max(10).optional().default(''),
  csosn: z.string().max(10).optional().default(''),
  icms_rate: z.coerce.number().min(0).optional().nullable(),
  pis_rate: z.coerce.number().min(0).optional().nullable(),
  cofins_rate: z.coerce.number().min(0).optional().nullable(),
  tax_regime: z.string().max(50).optional().default(''),
  cest: z.string().max(10).optional().default(''),

  // Logística (campos internos — armazenados mas sem UI dedicada)
  freight_class: z.string().max(50).optional().default(''),
  default_carrier: z.string().max(100).optional().default(''),
  shipping_weight_kg: z.coerce.number().min(0).optional().nullable(),
  shipping_width_cm: z.coerce.number().min(0).optional().nullable(),
  shipping_height_cm: z.coerce.number().min(0).optional().nullable(),
  shipping_length_cm: z.coerce.number().min(0).optional().nullable(),
  cubic_weight: z.coerce.number().min(0).optional().nullable(),
  requires_special_shipping: z.boolean().default(false),
  shipping_notes: z.string().max(500).optional().default(''),

  // Comercial
  lead_time_days: z.coerce.number().int().min(0).optional().nullable(),
  product_type: z.string().max(50).optional().default('product'),
  supply_mode: z.string().max(100).optional().default(''),
  warranty_months: z.coerce.number().int().min(0).optional().nullable(),
  gender: z.string().max(50).optional().default(''),

  // SEO
  meta_title: z.string().max(200).optional().default(''),
  meta_description: z.string().max(500, 'Meta descrição muito longa').optional().default(''),
  meta_keywords: z.string().max(500).optional().default(''), // comma-separated
  slug: z.string().max(300).optional().default(''),
  canonical_url: z.string().max(500).optional().default(''),

  // Mídia extra
  video_url: z.string().max(500).optional().default(''),

  // Texto marketing
  key_benefits: z.string().max(2000).optional().default(''),
  use_cases: z.string().max(2000).optional().default(''),
});

export type ProductFormData = z.infer<typeof productFormSchema>;

export const defaultFormValues: ProductFormData = {
  sku: '',
  name: '',
  description: '',
  short_description: '',
  brand: '',
  category_id: '',
  supplier_id: '',
  supplier_reference: '',
  supplier_product_url: '',
  sale_price: 0,
  cost_price: 0,
  suggested_price: null,
  stock_quantity: 10000,
  min_quantity: 1,
  min_order_quantity: null,
  stock_unit: 'un',
  height_cm: null,
  width_cm: null,
  length_cm: null,
  diameter_cm: null,
  weight_g: null,
  capacity_ml: null,
  internal_height_cm: null,
  internal_width_cm: null,
  internal_length_cm: null,
  internal_diameter_cm: null,
  packing_type: '',
  box_width_mm: null,
  box_height_mm: null,
  box_length_mm: null,
  box_weight_kg: null,
  box_quantity: null,
  box_inner_quantity: null,
  box_volume_cm3: null,
  box_internal_height_cm: null,
  box_internal_width_cm: null,
  box_internal_length_cm: null,
  packaging_material: '',
  packaging_color: '',
  packaging_finish: '',
  is_active: true,
  is_featured: false,
  is_bestseller: false,
  is_new: false,
  is_on_sale: false,
  is_featured_expires_at: null,
  is_bestseller_expires_at: null,
  is_new_expires_at: null,
  is_on_sale_expires_at: null,
  is_kit: false,
  has_commercial_packaging: false,
  is_imported: false,
  is_textil: false,
  is_thermal: false,
  allows_personalization: true,
  has_gift_box: false,
  has_optional_packaging: false,
  ncm_code: '',
  ean: '',
  gtin: '',
  ipi_rate: null,
  country_of_origin: '',
  cfop: '',
  csosn: '',
  icms_rate: null,
  pis_rate: null,
  cofins_rate: null,
  tax_regime: '',
  cest: '',
  freight_class: '',
  default_carrier: '',
  shipping_weight_kg: null,
  shipping_width_cm: null,
  shipping_height_cm: null,
  shipping_length_cm: null,
  cubic_weight: null,
  requires_special_shipping: false,
  shipping_notes: '',
  lead_time_days: null,
  product_type: 'product',
  supply_mode: '',
  warranty_months: null,
  gender: '',
  meta_title: '',
  meta_description: '',
  meta_keywords: '',
  slug: '',
  canonical_url: '',
  video_url: '',
  key_benefits: '',
  use_cases: '',
};
