-- T37b-1: Convert first batch of CANDIDATE functions to SECURITY INVOKER
-- These are lookup/read functions and user-scoped operations that don't need elevated privileges.
-- Impact: part of 210 → 0 authenticated_security_definer_function_executable violations.

ALTER FUNCTION public._get_user_primary_role(uuid) SECURITY INVOKER;
ALTER FUNCTION public.acquire_ai_quota(uuid, text, text) SECURITY INVOKER;
ALTER FUNCTION public.block_ip_temp(text, text, integer) SECURITY INVOKER;
ALTER FUNCTION public.can_manage_quotes(uuid) SECURITY INVOKER;
ALTER FUNCTION public.check_ai_quota(uuid) SECURITY INVOKER;
ALTER FUNCTION public.check_auth_throttling(text, text) SECURITY INVOKER;
ALTER FUNCTION public.check_geo_country_allowed(text) SECURITY INVOKER;
ALTER FUNCTION public.check_hardening_status() SECURITY INVOKER;
ALTER FUNCTION public.check_ip_access(text) SECURITY INVOKER;
ALTER FUNCTION public.check_owner_email(uuid) SECURITY INVOKER;
ALTER FUNCTION public.check_rate_limit(text, text, integer, integer, integer) SECURITY INVOKER;
ALTER FUNCTION public.clear_auth_attempts(text) SECURITY INVOKER;
ALTER FUNCTION public.clear_user_token_revocations(uuid) SECURITY INVOKER;
ALTER FUNCTION public.compare_quote_snapshots(uuid, integer, integer) SECURITY INVOKER;
ALTER FUNCTION public.compute_quote_snapshot_hash(uuid) SECURITY INVOKER;
ALTER FUNCTION public.consume_step_up_token(text, step_up_action, text) SECURITY INVOKER;
ALTER FUNCTION public.convert_quote_to_order(uuid, uuid, uuid) SECURITY INVOKER;
ALTER FUNCTION public.create_organization_with_owner(text, text) SECURITY INVOKER;
ALTER FUNCTION public.ensure_default_favorite_list(uuid) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_create_conversation(text, text) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_get_conversation(uuid) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_get_messages(uuid, integer) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_log_event(uuid, text, text, text, text, integer) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_send_message(uuid, text, text) SECURITY INVOKER;
ALTER FUNCTION public.expert_chat_update_status(text, text) SECURITY INVOKER;
ALTER FUNCTION public.fn_calculate_health_score() SECURITY INVOKER;
ALTER FUNCTION public.fn_capacity_forecast(integer) SECURITY INVOKER;
ALTER FUNCTION public.fn_check_geo_access(text) SECURITY INVOKER;
ALTER FUNCTION public.fn_create_quote_v3(jsonb, jsonb) SECURITY INVOKER;
ALTER FUNCTION public.fn_get_customization_price(uuid, integer, integer, numeric, numeric, integer) SECURITY INVOKER;
ALTER FUNCTION public.fn_get_product_customization_options(uuid) SECURITY INVOKER;
ALTER FUNCTION public.fn_product_market_intelligence(uuid, integer) SECURITY INVOKER;
ALTER FUNCTION public.fn_save_quote_draft(jsonb) SECURITY INVOKER;
ALTER FUNCTION public.force_user_logout(uuid) SECURITY INVOKER;
ALTER FUNCTION public.generate_step_up_challenge(step_up_action, text) SECURITY INVOKER;
ALTER FUNCTION public.get_active_commemorative_dates() SECURITY INVOKER;
ALTER FUNCTION public.get_active_novelties(character varying, integer, integer, boolean) SECURITY INVOKER;
ALTER FUNCTION public.get_active_step_up_tokens() SECURITY INVOKER;
ALTER FUNCTION public.get_all_material_groups_safe() SECURITY INVOKER;
ALTER FUNCTION public.get_all_material_types_safe() SECURITY INVOKER;
ALTER FUNCTION public.get_app_health_summary(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_app_setting(character varying) SECURITY INVOKER;
ALTER FUNCTION public.get_auto_test_job_status(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_best_supplier_for_quantity(uuid, integer, character varying) SECURITY INVOKER;
ALTER FUNCTION public.get_bundle_suggestions(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_category_descendants(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_client_seasonality(uuid, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_client_top_products(uuid, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_cloudflare_stats() SECURITY INVOKER;
ALTER FUNCTION public.get_collections_weekly_count(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_commemorative_dates_by_product(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_commemorative_dates_by_variant(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_connection_failure_window_minutes() SECURITY INVOKER;
ALTER FUNCTION public.get_connections_auto_test_interval() SECURITY INVOKER;
ALTER FUNCTION public.get_favorites_weekly_count(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_full_scope_grants() SECURITY INVOKER;
ALTER FUNCTION public.get_industry_benchmark_stats(uuid[], integer) SECURITY INVOKER;
ALTER FUNCTION public.get_industry_seasonality(uuid[], integer) SECURITY INVOKER;
ALTER FUNCTION public.get_industry_top_products(uuid[], integer, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_login_attempts_status(text, text, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_material_types_by_group_id(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_material_types_by_group_slug(text) SECURITY INVOKER;
ALTER FUNCTION public.get_materials_complete_safe() SECURITY INVOKER;
ALTER FUNCTION public.get_mcp_key_status(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_my_grantor_status() SECURITY INVOKER;
ALTER FUNCTION public.get_novelties_stats() SECURITY INVOKER;
ALTER FUNCTION public.get_pending_images_for_sync(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_pending_videos_for_sync(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_platform_failure_metrics(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_step_up_audit(uuid, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_top_collected_products(integer, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_top_compared_products(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_top_favorited_products(integer, integer) SECURITY INVOKER;
ALTER FUNCTION public.get_unread_count() SECURITY INVOKER;
ALTER FUNCTION public.get_upcoming_commemorative_dates(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_user_org_ids(uuid) SECURITY INVOKER;
ALTER FUNCTION public.get_user_recent_comparisons(integer) SECURITY INVOKER;
ALTER FUNCTION public.get_user_role_history(uuid) SECURITY INVOKER;
