
-- ====== ONDA 1.1 — STORAGE HARDENING ======
-- Goal: bloquear list() massivo nos buckets públicos, mantendo acesso direto por URL.
-- Strategy:
--  1. Tornar buckets privados (assets continuam acessíveis via URL pública na CDN do Supabase porque as policies SELECT permitem leitura por nome conhecido).
--  2. Remover policies amplas que permitiam SELECT sem filtro -> habilitavam list()/enumeration.
--  3. Manter "Direct read X" policies (que ainda exigem name IS NOT NULL) mas reforçar para exigir caller autenticado OU service_role; anon só lê via signed URL.
--  4. Permitir list() apenas para admins.

-- 1. Make buckets private (URLs continuam funcionando via SELECT policy + getPublicUrl pattern; recomenda-se signed URLs para novos uploads)
UPDATE storage.buckets SET public = false
WHERE id IN ('personalization-images', 'product-videos', 'supplier-logos', 'component-media');

-- 2. Drop overly-broad SELECT policies that allowed unrestricted list()
DROP POLICY IF EXISTS "Authenticated can read component-media" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can read personalization-images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can read product-videos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can read supplier-logos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can read protected buckets" ON storage.objects;

-- 3. Drop and recreate "Direct read" policies to require authenticated role
--    (anon clients can still read via signed URLs generated by the backend)
DROP POLICY IF EXISTS "Direct read component-media" ON storage.objects;
DROP POLICY IF EXISTS "Direct read personalization-images" ON storage.objects;
DROP POLICY IF EXISTS "Direct read product-videos" ON storage.objects;
DROP POLICY IF EXISTS "Direct read supplier-logos" ON storage.objects;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated direct read component-media') THEN
    CREATE POLICY "Authenticated direct read component-media"
    ON storage.objects FOR SELECT TO authenticated
    USING (bucket_id = 'component-media' AND name IS NOT NULL AND length(name) > 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated direct read personalization-images') THEN
    CREATE POLICY "Authenticated direct read personalization-images"
    ON storage.objects FOR SELECT TO authenticated
    USING (bucket_id = 'personalization-images' AND name IS NOT NULL AND length(name) > 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated direct read product-videos') THEN
    CREATE POLICY "Authenticated direct read product-videos"
    ON storage.objects FOR SELECT TO authenticated
    USING (bucket_id = 'product-videos' AND name IS NOT NULL AND length(name) > 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated direct read supplier-logos') THEN
    CREATE POLICY "Authenticated direct read supplier-logos"
    ON storage.objects FOR SELECT TO authenticated
    USING (bucket_id = 'supplier-logos' AND name IS NOT NULL AND length(name) > 0);
  END IF;
END $$;

-- 4. Admins can list (full SELECT without name guard) for management UIs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Admins can list protected buckets') THEN
    CREATE POLICY "Admins can list protected buckets"
    ON storage.objects FOR SELECT TO authenticated
    USING (
      bucket_id = ANY (ARRAY['supplier-logos','product-videos','personalization-images','component-media'])
      AND has_role(auth.uid(), 'admin'::app_role)
    );
  END IF;
END $$;
